Dynamic Hyperparameter Path Agent Extension
SDNNetSim/FUSION pull request #80
Opened 2024-12-16 16:54 UTC by ryanmccann1024

## Description
These changes relate to the latest OFC submission. The main functionality added is dynamic hyperparameter generation with an external library for the reinforcement learning path agents.

## Type of Change
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How has this change been tested?
This change will be tested shortly after merging from main and comparing new changes added with GitHub's "changes" tab.

- [ ] Test TBD

**Test Configuration**:
* Operating System: Fedora 39
* Python version: 3.11

## Does change comply with project standards and guideline?
Standards and guidelines can be found on the [Project Homepage](https://github.com/SDNNetSim/SDON_simulator).
- [X] Commit formatting
- [X] Versioning
- [X] Code style
- [X] Coding guidelines
- [ ] Unit Testing

2024-12-16 17:08 UTC, ryanmccann1024 reviewed
First merge upstream changes and address every comment as completed for the next round of reviews to be conducted.

2024-12-16 17:08 UTC, ryanmccann1024 commented on helper_scripts/sim_helpers.py
> +
Tests need to be listed here for this many additions.

2024-12-16 17:08 UTC, ryanmccann1024 commented on run_rl_sim.py
> +
List tests for run_rl_sim.

2024-12-16 17:08 UTC, ryanmccann1024 commented on run_sim.py
> +        # arr_rate_dict = self.properties['arrival_rate']
Tests need to be listed.

2024-12-16 17:08 UTC, ryanmccann1024 commented on src/spectrum_assignment.py
>                      self.spec_help_obj.curr_band = channel_dict['band']
If something needs to be double checked then a test probably needs to be created.

2024-12-16 17:08 UTC, ryanmccann1024 commented on tests/test_multi_agent_helpers.py
> +            'max_iters': 100,
List these tests in the PR for organizational purposes.

2024-12-16 17:08 UTC, ryanmccann1024 commented on tests/test_ql_helpers.py
> +        # fixme: QLearningHelpers does not have a 'decay_epsilon' member anymore
Lists these tests in the PR.

2024-12-16 17:17 UTC, ryanmccann1024 commented
Update: I should change the PR template to ensure the user has updated our UML chart if needed.

2024-12-17 14:07 UTC, kbempah commented on gui_scripts/gui_helpers/action_helpers.py
This hasn't been pushed, but a GUI defaults dictionary is in the works. It's purpose is to address hardcodings like this one.

2024-12-17 14:15 UTC, kbempah commented on helper_scripts/multi_agent_helpers.py
> +        last_reward = self.reward_list[1]
We can unpack here as well.

2024-12-17 14:21 UTC, kbempah commented on helper_scripts/ql_helpers.py
>          self.path_levels = engine_props['path_levels']
What does this mean?

2024-12-17 14:34 UTC, kbempah commented on run_rl_sim.py
> +        _ = self._handle_test_train_obs(curr_req=curr_req)
If return value is not used, it shouldn't be saved

2024-12-17 14:43 UTC, kbempah commented on tests/test_multi_agent_helpers.py
> +        self.assertEqual(reward, -5)
How come?

2024-12-17 14:51 UTC, kbempah requested changes
Looks great. Suggested a few changes

2025-01-08 20:02 UTC, kbempah approved these changes

2025-01-08 21:14 UTC, merged